version: '3.7'
services:
  mongodb:
    image: mongo:latest
    hostname: localhost
    environment:
      - MONGO_DB_HOST=localhost
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
